### PR TITLE
Improve, simplify and rename release script: /bin/update_version.sh

### PR DESCRIPTION
**Pull request by alejandro-colomar**

### CODE REVIEW

**Review by scolomar — CHANGES_REQUESTED** [review]
This line does not work and breaks the code:
`source	lib/libalx/sh/sysexits.sh`

**Comment by alejandro-colomar** [comment]
Show me where it doesn't work.  It works for me.  It works in bash (but doesn't work for other shells).

**Comment by scolomar** [comment]
> Show me where it doesn't work. It works for me. It works in bash (but doesn't work for other shells).

I already tested in AWS.

Could you please show me the nohup.out of your deployment?

**Comment by alejandro-colomar** [comment]
That line works perfectly.  I've been using it in my projects and it works fine.  It might be your problem.
```


alex-431681714777:~/environment/www (master) $ 
alex-431681714777:~/environment/www (master) $ ls -l lib/libalx/sh/sysexits.sh 
-rw-rw-r-- 1 ec2-user ec2-user 4555 Jun 13 10:08 lib/libalx/sh/sysexits.sh
alex-431681714777:~/environment/www (master) $ cat lib/libalx/sh/sysexits.sh 
##      source  /lib/libalx/sh/sysexits.sh
################################################################################
##      Copyright (C) 2020        Alejandro Colomar Andrés                    ##
##      SPDX-License-Identifier:  BSD-2-Clause                                ##
################################################################################
##
## Exit codes (based on <sysexits.h>)
##
##  SYSEXITS.H -- Exit status codes for system programs.
##
##      This include file attempts to categorize possible error
##      exit statuses for system programs, notably delivermail
##      and the Berkeley network.
##
##      Error numbers begin at EX__BASE to reduce the possibility of
##      clashing with other exit statuses that random programs may
##      already return.  The meaning of the codes is approximately
##      as follows:
##
##      EX_USAGE -- The command was used incorrectly, e.g., with
##              the wrong number of arguments, a bad flag, a bad
##              syntax in a parameter, or whatever.
##      EX_DATAERR -- The input data was incorrect in some way.
##              This should only be used for user's data & not
##              system files.
##      EX_NOINPUT -- An input file (not a system file) did not
##              exist or was not readable.  This could also include
##              errors like "No message" to a mailer (if it cared
##              to catch it).
##      EX_NOUSER -- The user specified did not exist.  This might
##              be used for mail addresses or remote logins.
##      EX_NOHOST -- The host specified did not exist.  This is used
##              in mail addresses or network requests.
##      EX_UNAVAILABLE -- A service is unavailable.  This can occur
##              if a support program or file does not exist.  This
##              can also be used as a catchall message when something
##              you wanted to do doesn't work, but you don't know
##              why.
##      EX_SOFTWARE -- An internal software error has been detected.
##              This should be limited to non-operating system related
##              errors as possible.
##      EX_OSERR -- An operating system error has been detected.
##              This is intended to be used for such things as "cannot
##              fork", "cannot create pipe", or the like.  It includes
##              things like getuid returning a user that does not
##              exist in the passwd file.
##      EX_OSFILE -- Some system file (e.g., /etc/passwd, /etc/utmp,
##              etc.) does not exist, cannot be opened, or has some
##              sort of error (e.g., syntax error).
##      EX_CANTCREAT -- A (user specified) output file cannot be
##              created.
##      EX_IOERR -- An error occurred while doing I/O on some file.
##      EX_TEMPFAIL -- temporary failure, indicating something that
##              is not really an error.  In sendmail, this means
##              that a mailer (e.g.) could not create a connection,
##              and the request should be reattempted later.
##      EX_PROTOCOL -- the remote system returned something that
##              was "not possible" during a protocol exchange.
##      EX_NOPERM -- You did not have sufficient permission to
##              perform the operation.  This is not intended for
##              file system problems, which should use NOINPUT or
##              CANTCREAT, but rather for higher level permissions.
##      EX_CONFIG -- Something was found in an unconfigured or
##              misconfigured state.
##
################################################################################


################################################################################
##      include guard                                                         ##
################################################################################
if [ -n "${SYSEXITS_H}" ]; then
        return;
fi
SYSEXITS_H="/lib/libalx/sh/sysexits.sh included";


################################################################################
##      definitions                                                           ##
################################################################################
EX_OK=0;                ## successful termination

EX__BASE=64;            ## base value for error messages

EX_USAGE=64;            ## command line usage error
EX_DATAERR=65;          ## data format error
EX_NOINPUT=66;          ## cannot open input
EX_NOUSER=67;           ## addressee unknown
EX_NOHOST=68;           ## host name unknown
EX_UNAVAILABLE=69;      ## service unavailable
EX_SOFTWARE=70;         ## internal software error
EX_OSERR=71;            ## system error (e.g., can't fork)
EX_OSFILE=72;           ## critical OS file missing
EX_CANTCREAT=73;        ## can't create (user) output file
EX_IOERR=74;            ## input/output error
EX_TEMPFAIL=75;         ## temp failure; user is invited to retry
EX_PROTOCOL=76;         ## remote error in protocol
EX_NOPERM=77;           ## permission denied
EX_CONFIG=78;           ## configuration error

EX__MAX=78;             ## maximum listed value


################################################################################
##      end of file                                                           ##
################################################################################
alex-431681714777:~/environment/www (master) $ source lib/libalx/sh/sysexits.sh 
alex-431681714777:~/environment/www (master) $ echo $EX__BASE
64
alex-431681714777:~/environment/www (master) $ ./bin/update_version.sh 
+ source lib/libalx/sh/sysexits.sh
++ '[' -n '' ']'
++ SYSEXITS_H='/lib/libalx/sh/sysexits.sh included'
++ EX_OK=0
++ EX__BASE=64
++ EX_USAGE=64
++ EX_DATAERR=65
++ EX_NOINPUT=66
++ EX_NOUSER=67
++ EX_NOHOST=68
++ EX_UNAVAILABLE=69
++ EX_SOFTWARE=70
++ EX_OSERR=71
++ EX_OSFILE=72
++ EX_CANTCREAT=73
++ EX_IOERR=74
++ EX_TEMPFAIL=75
++ EX_PROTOCOL=76
++ EX_NOPERM=77
++ EX_CONFIG=78
++ EX__MAX=78
+ MAX_ARGC=1
+ argc=0
+ '[' 0 -gt 1 ']'
+ main '' 0
+ local version=
+ local argc=0
+ '[' 0 -eq 0 ']'
++ git branch --show-current
error: unknown option `show-current'
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
   or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
   or: git branch [<options>] [-r] (-d | -D) <branch-name>...
   or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
   or: git branch [<options>] [-r | -a] [--points-at]
   or: git branch [<options>] [-r | -a] [--format]

Generic options
    -v, --verbose         show hash and subject, give twice for upstream branch
    -q, --quiet           suppress informational messages
    -t, --track           set up tracking mode (see git-pull(1))
    --set-upstream        change upstream info
    -u, --set-upstream-to <upstream>
                          change the upstream info
    --unset-upstream      Unset the upstream info
    --color[=<when>]      use colored output
    -r, --remotes         act on remote-tracking branches
    --contains <commit>   print only branches that contain the commit
    --no-contains <commit>
                          print only branches that don't contain the commit
    --abbrev[=<n>]        use <n> digits to display SHA-1s

Specific git-branch actions:
    -a, --all             list both remote-tracking and local branches
    -d, --delete          delete fully merged branch
    -D                    delete branch (even if not merged)
    -m, --move            move/rename a branch and its reflog
    -M                    move/rename a branch, even if target exists
    --list                list branch names
    -l, --create-reflog   create the branch's reflog
    --edit-description    edit the description for the branch
    -f, --force           force creation, move/rename, deletion
    --merged <commit>     print only branches that are merged
    --no-merged <commit>  print only branches that are not merged
    --column[=<style>]    list branches in columns
    --sort <key>          field name to sort on
    --points-at <object>  print only branches of the object
    -i, --ignore-case     sorting and filtering are case insensitive
    --format <format>     format to use for the output

+ version=
+ update_version ''
+ local version=
+ sed '/branch_app=/s/".*"/""/' -i ./etc/docker-aws/config.sh
+ sed '/--branch/s/".*"/""/' -i ./etc/docker/build/Dockerfile
+ sed '/alejandrocolomar\/www:/s/www:.*"/www:"/' -i ./etc/docker/swarm/docker-compose.yaml
alex-431681714777:~/environment/www (master) $ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   etc/docker-aws/config.sh
        modified:   etc/docker/build/Dockerfile
        modified:   etc/docker/swarm/docker-compose.yaml

no changes added to commit (use "git add" and/or "git commit -a")
alex-431681714777:~/environment/www (master) $ git diff
diff --git a/etc/docker-aws/config.sh b/etc/docker-aws/config.sh
index eaa897f..42dbb42 100644
--- a/etc/docker-aws/config.sh
+++ b/etc/docker-aws/config.sh
@@ -40,7 +40,7 @@ TypeManager="t3a.nano"
 TypeWorker="t3a.nano"
 ########################################
 apps=" docker-compose.yaml "
-branch_app="master"
+branch_app=""
 repository_app="www"
 username_app="alejandro-colomar"
 
diff --git a/etc/docker/build/Dockerfile b/etc/docker/build/Dockerfile
index d436981..221dfaf 100644
--- a/etc/docker/build/Dockerfile
+++ b/etc/docker/build/Dockerfile
@@ -15,7 +15,7 @@ RUN                                                                   \
 RUN                                                                    \
        git clone                                                       \
                --single-branch                                         \
-               --branch "master"                                       \
+               --branch ""                                     \
                https://github.com/alejandro-colomar/www.git            \
                /usr/local/src/www
 
diff --git a/etc/docker/swarm/docker-compose.yaml b/etc/docker/swarm/docker-compose.yaml
index f4e4041..1cfceb0 100644
--- a/etc/docker/swarm/docker-compose.yaml
+++ b/etc/docker/swarm/docker-compose.yaml
@@ -34,7 +34,7 @@ services:
             replicas: 3
             restart_policy:
                 condition: any
-        image: "alejandrocolomar/www:master"
+        image: "alejandrocolomar/www:"
         ports:
         -   30001:80
 
alex-431681714777:~/environment/www (master) $ 
```

**Comment by scolomar** [comment]
Those logs are not the logs of a deployment in AWS. Have you successfully deployed in AWS? Could you please show the logs of such a deployment?

**Comment by alejandro-colomar** [comment]
This is a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) proving that line doesn't fail (2 examples, actually).

The problem is in writing code in a README.  Shell code should go in .sh files.

I won't prove it by forking your project because that would involve a lot of work to prove something that is already proven.

**Pull request closed without merging**
